import esbuild from "esbuild";
import os from "os";
import path from "path";
import fs from "fs";
const VAULT_PLUGIN_DIR = path.join(os.homedir(), "Library/Mobile Documents/iCloud~md~obsidian/Documents/MyObsidian/.obsidian/plugins/my-html-card");
import process from "process";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        // "@codemirror/autocomplete",
        // "@codemirror/collab",
        // "@codemirror/commands",
        // "@codemirror/language", // We bundle language to ensure we have the right version for lang-html
        // "@codemirror/lint",
        // "@codemirror/search",
        // "@codemirror/state", // Obsidian provides this
        // "@codemirror/view", // Obsidian provides this
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

// Also copy build artifacts into the local vault plugin dir for testing.
function syncToVault() {
    try {
        fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
        for (const f of ["main.js", "manifest.json", "styles.css"]) {
            if (fs.existsSync(f)) fs.copyFileSync(f, path.join(VAULT_PLUGIN_DIR, f));
        }
    } catch (e) {
        console.error("vault sync failed:", e);
    }
}

if (prod) {
    await context.rebuild();
    syncToVault();
    process.exit(0);
} else {
    await context.watch();
}
