/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HtmlCardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var HtmlCardPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.observer = null;
    this.processedEmbeds = /* @__PURE__ */ new WeakSet();
    this.embedCounter = 0;
    this.embedGuards = [];
    // Inspect mode state
    this.inspectMode = false;
    this.inspectLeaf = null;
    this.inspectStyleEl = null;
    this.escHandler = null;
  }
  async onload() {
    this.inspectStyleEl = document.createElement("style");
    this.inspectStyleEl.id = "html-card-inspect-style";
    this.inspectStyleEl.textContent = `
            .cm-editor:not(.cm-focused) .cm-selectionBackground {
                background-color: rgba(37, 99, 235, 0.25) !important;
            }
        `;
    document.head.appendChild(this.inspectStyleEl);
    this.registerMarkdownCodeBlockProcessor("html-block", (source, el, ctx) => {
      this.processHtmlCard(source, el, ctx);
    });
    this.registerMarkdownCodeBlockProcessor("html", (source, el, ctx) => {
      const sectionInfo = ctx.getSectionInfo(el);
      if (sectionInfo) {
        const fenceLine = sectionInfo.text.split("\n")[sectionInfo.lineStart];
        if (fenceLine && /```html\s+card/i.test(fenceLine)) {
          this.processHtmlCard(source, el, ctx);
          return;
        }
      }
      const pre = el.createEl("pre");
      const code = pre.createEl("code", { cls: "language-html" });
      code.textContent = source;
      const Prism = window.Prism;
      if (Prism == null ? void 0 : Prism.highlightElement) {
        Prism.highlightElement(code);
      }
    });
    this.registerMarkdownCodeBlockProcessor("html-card", (source, el, ctx) => {
      this.processHtmlCard(source, el, ctx);
    });
    this.embedCounter = 0;
    this.observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        mutation.addedNodes.forEach((node) => {
          var _a, _b;
          if (!(node instanceof HTMLElement))
            return;
          const embeds = ((_a = node.matches) == null ? void 0 : _a.call(node, ".internal-embed")) ? [node] : Array.from(((_b = node.querySelectorAll) == null ? void 0 : _b.call(node, ".internal-embed")) || []);
          for (const embed of embeds) {
            if (this.processedEmbeds.has(embed))
              continue;
            const src = embed.getAttribute("src") || "";
            if (/\.html?$/i.test(src)) {
              this.processedEmbeds.add(embed);
              const id = ++this.embedCounter;
              this.replaceHtmlEmbed(embed, src, id);
            }
          }
        });
      }
    });
    this.observer.observe(document.body, { childList: true, subtree: true });
    this.addCommand({
      id: "toggle-inspect-mode",
      name: "Toggle Inspect Mode",
      callback: () => this.setInspectMode(!this.inspectMode)
    });
    this.escHandler = (e) => {
      if (e.key === "Escape" && this.inspectMode) {
        this.setInspectMode(false);
      }
    };
    document.addEventListener("keydown", this.escHandler);
  }
  // ========================
  // Inspect Mode
  // ========================
  setInspectMode(on) {
    var _a;
    this.inspectMode = on;
    document.querySelectorAll(".html-card-container").forEach((c) => {
      var _a2;
      if (on) {
        c.classList.add("html-card-inspecting");
      } else {
        c.classList.remove("html-card-inspecting");
        (_a2 = c.shadowRoot) == null ? void 0 : _a2.querySelectorAll(".hc-hover").forEach(
          (el) => el.classList.remove("hc-hover")
        );
      }
    });
    if (on) {
      const firstCard = document.querySelector(".html-card-container");
      if ((_a = firstCard == null ? void 0 : firstCard.dataset) == null ? void 0 : _a.sourceFile) {
        this.ensureSourceLeaf(firstCard.dataset.sourceFile);
      }
    }
  }
  // ========================
  // Embed replacement (![[file.html]])
  // ========================
  async replaceHtmlEmbed(embedEl, src, id) {
    const linkPath = src || embedEl.getAttribute("alt") || "";
    const file = this.app.vault.getAbstractFileByPath(linkPath) || this.app.metadataCache.getFirstLinkpathDest(linkPath, "");
    if (!(file instanceof import_obsidian.TFile))
      return;
    await new Promise((r) => setTimeout(r, 150));
    embedEl.empty();
    embedEl.style.display = "block";
    embedEl.style.height = "auto";
    embedEl.style.maxHeight = "none";
    embedEl.style.overflow = "visible";
    try {
      const content = await this.app.vault.read(file);
      const container = embedEl.createDiv({ cls: "html-card-container" });
      let sourceFilePath = file.path;
      let lineOffset = 0;
      if (file.extension === "md") {
        const lines = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
          if (/^```html(?:-block|[- ]card)/.test(lines[i].trim())) {
            lineOffset = i + 1;
            break;
          }
        }
        const match = content.match(/```html(?:-block|[- ]card)\s*\n([\s\S]*?)```/);
        if (match) {
          this.renderHtmlContent(match[1], container, sourceFilePath, lineOffset);
        }
      } else {
        this.renderHtmlContent(content, container, sourceFilePath, 0);
      }
      const guard = new MutationObserver((mutations) => {
        for (const m of mutations) {
          m.addedNodes.forEach((node) => {
            if (node instanceof HTMLElement && !node.classList.contains("html-card-container")) {
              node.remove();
            }
          });
        }
      });
      guard.observe(embedEl, { childList: true });
      this.embedGuards.push(guard);
    } catch (e) {
      console.error(`[html-card] embed #${id}: render failed`, e);
    }
  }
  // ========================
  // Code block processor
  // ========================
  async processHtmlCard(source, el, ctx) {
    el.empty();
    const container = el.createDiv({ cls: "html-card-container" });
    try {
      let sourceFilePath = ctx.sourcePath;
      let lineOffset = 0;
      const wikiLinkMatch = source.trim().match(/^\[\[(.+?)\]\]$/);
      if (wikiLinkMatch) {
        const linkText = wikiLinkMatch[1];
        const sourceFile = this.app.metadataCache.getFirstLinkpathDest(linkText, ctx.sourcePath);
        if (sourceFile && sourceFile instanceof import_obsidian.TFile) {
          const fileContent = await this.app.vault.read(sourceFile);
          sourceFilePath = sourceFile.path;
          if (sourceFile.extension === "md") {
            const lines = fileContent.split("\n");
            for (let i = 0; i < lines.length; i++) {
              if (/^```html(?:-block|[- ]card)/.test(lines[i].trim())) {
                lineOffset = i + 1;
                break;
              }
            }
            const match = fileContent.match(/```html[- ]card\s*\n([\s\S]*?)```/);
            source = match ? match[1] : fileContent;
          } else {
            source = fileContent;
          }
        } else {
          throw new Error(`File not found: [[${linkText}]]`);
        }
      } else {
        const sectionInfo = ctx.getSectionInfo(el);
        if (sectionInfo) {
          lineOffset = sectionInfo.lineStart + 1;
        }
      }
      this.renderHtmlContent(source, container, sourceFilePath, lineOffset);
    } catch (error) {
      container.empty();
      const d = container.createDiv();
      Object.assign(d.style, {
        display: "block",
        color: "red",
        border: "1px solid red",
        padding: "10px",
        fontFamily: "sans-serif"
      });
      d.innerText = "Error: " + String(error);
    }
  }
  // ========================
  // Core renderer
  // ========================
  renderHtmlContent(source, hostEl, sourceFilePath, lineOffset) {
    var _a;
    const shadow = hostEl.attachShadow({ mode: "open" });
    if (sourceFilePath)
      hostEl.dataset.sourceFile = sourceFilePath;
    if (lineOffset !== void 0)
      hostEl.dataset.lineOffset = String(lineOffset);
    const style = document.createElement("style");
    style.textContent = `
            :host {
                display: block; width: 100%; background-color: white; color: black;
                font-family: Times, serif; font-size: 16px; line-height: normal;
                margin: 0; padding: 0;
                border: 1px solid var(--background-modifier-border, #e0e0e0);
                border-radius: 6px;
                text-decoration: none; text-align: left;
                vertical-align: baseline; letter-spacing: normal; word-spacing: normal;
                text-transform: none; text-indent: 0;
            }
            html, body { display: block; margin: 8px; padding: 0; width: auto; height: auto; }
            head, meta, title, link, script { display: none; }
            div { display: block; } span { display: inline; }
            p { display: block; margin: 1em 0; }
            strong, b { font-weight: bold; } em, i { font-style: italic; }
            a { color: -webkit-link; text-decoration: underline; cursor: pointer; }
            h1 { display: block; font-size: 2em; margin: 0.67em 0; font-weight: bold; }
            h2 { display: block; font-size: 1.5em; margin: 0.83em 0; font-weight: bold; }
            h3 { display: block; font-size: 1.17em; margin: 1em 0; font-weight: bold; }
            h4 { display: block; font-size: 1em; margin: 1.33em 0; font-weight: bold; }
            h5 { display: block; font-size: 0.83em; margin: 1.67em 0; font-weight: bold; }
            h6 { display: block; font-size: 0.67em; margin: 2.33em 0; font-weight: bold; }
            ul, menu, dir { display: block; list-style-type: disc; margin-block-start: 1em; margin-block-end: 1em; padding-inline-start: 40px; }
            ol { display: block; list-style-type: decimal; margin-block-start: 1em; margin-block-end: 1em; padding-inline-start: 40px; }
            li { display: list-item; }
            table { display: table; border-collapse: separate; border-spacing: 2px; }
            tr { display: table-row; } td, th { display: table-cell; padding: 1px; }
            thead { display: table-header-group; } tbody { display: table-row-group; }
            img { display: inline; max-width: 100%; }
            * { box-sizing: content-box; }

            /* Inspect: hover = outline + tinted background */
            :host(.html-card-inspecting) [data-source-line] {
                cursor: crosshair !important;
            }
            :host(.html-card-inspecting) [data-source-line].hc-hover {
                outline: 2px solid rgba(231, 76, 60, 0.7) !important;
                outline-offset: 1px;
                background: rgba(231, 76, 60, 0.06) !important;
            }
        `;
    shadow.appendChild(style);
    const lines = source.split("\n");
    let inBlock = false;
    const taggedLines = lines.map((line, i) => {
      const trimmed = line.trim();
      if (/<(style|script)[\s>]/i.test(trimmed))
        inBlock = true;
      if (/<\/(style|script)>/i.test(trimmed)) {
        inBlock = false;
        return line;
      }
      if (inBlock)
        return line;
      return line.replace(
        /(<(?!\/|!|style|script)[a-zA-Z][^\s/>]*)([\s>])/i,
        `$1 data-source-line="${i + 1}"$2`
      );
    });
    const processedSource = taggedLines.join("\n").replace(
      /(<style[^>]*>)([\s\S]*?)(<\/style>)/gi,
      (_, open, css, close) => open + css.replace(/:root\b/g, ":host") + close
    );
    const template = document.createElement("template");
    template.innerHTML = processedSource;
    shadow.appendChild(template.content.cloneNode(true));
    this.executeScripts(shadow);
    const sourceFile = sourceFilePath || "";
    if (sourceFile.endsWith(".html") || sourceFile.endsWith(".htm"))
      return;
    let hoverDebounce = null;
    shadow.addEventListener("mouseover", (e) => {
      var _a2, _b;
      if (!this.inspectMode)
        return;
      const target = (_b = (_a2 = e.target).closest) == null ? void 0 : _b.call(_a2, "[data-source-line]");
      if (!target)
        return;
      shadow.querySelectorAll(".hc-hover").forEach((el) => el.classList.remove("hc-hover"));
      target.classList.add("hc-hover");
      if (hoverDebounce)
        clearTimeout(hoverDebounce);
      hoverDebounce = setTimeout(() => {
        const sourceLine = parseInt(target.dataset.sourceLine || "0");
        const filePath = hostEl.dataset.sourceFile || "";
        const offset = parseInt(hostEl.dataset.lineOffset || "0");
        this.scrollSourceToLine(filePath, offset + sourceLine - 1);
      }, 80);
    });
    shadow.addEventListener("mouseleave", () => {
      shadow.querySelectorAll(".hc-hover").forEach((el) => el.classList.remove("hc-hover"));
      if (hoverDebounce)
        clearTimeout(hoverDebounce);
    });
    const embedParent = (_a = hostEl.closest) == null ? void 0 : _a.call(hostEl, ".internal-embed");
    const handleInspectClick = (e) => {
      var _a2;
      if (!this.inspectMode)
        return;
      e.preventDefault();
      e.stopPropagation();
      e.stopImmediatePropagation();
      const path = e.composedPath();
      let lineEl = null;
      for (const el of path) {
        if ((_a2 = el.dataset) == null ? void 0 : _a2.sourceLine) {
          lineEl = el;
          break;
        }
        if (el === hostEl)
          break;
      }
      if (!lineEl)
        return;
      const sourceLine = parseInt(lineEl.dataset.sourceLine || "0");
      const filePath = hostEl.dataset.sourceFile || "";
      const offset = parseInt(hostEl.dataset.lineOffset || "0");
      const absLine = offset + sourceLine - 1;
      this.selectSourceLine(filePath, absLine);
      this.setInspectMode(false);
    };
    hostEl.addEventListener("click", handleInspectClick, true);
    if (embedParent) {
      embedParent.addEventListener("click", handleInspectClick, true);
    }
  }
  // ========================
  // Script execution (per-card sandbox)
  // ========================
  /**
   * Build a `document` proxy for a card. Element-lookup methods resolve against
   * the card's shadowRoot; everything else falls through to the real document.
   * This lets inline scripts that use bare `document.getElementById(...)` find
   * nodes that actually live inside the shadow tree.
   */
  makeDocumentProxy(shadow) {
    const realDoc = document;
    const scoped = {
      getElementById: (id) => {
        var _a;
        return shadow.getElementById ? shadow.getElementById(id) : shadow.querySelector(`#${((_a = window.CSS) == null ? void 0 : _a.escape) ? CSS.escape(id) : id}`);
      },
      querySelector: (sel) => shadow.querySelector(sel),
      querySelectorAll: (sel) => shadow.querySelectorAll(sel),
      getElementsByClassName: (cls) => shadow.querySelectorAll("." + cls.split(/\s+/).filter(Boolean).join(".")),
      getElementsByTagName: (tag) => shadow.querySelectorAll(tag)
    };
    return new Proxy(realDoc, {
      get(target, prop) {
        if (typeof prop === "string" && prop in scoped) {
          return scoped[prop];
        }
        const value = target[prop];
        return typeof value === "function" ? value.bind(target) : value;
      },
      set(target, prop, value) {
        target[prop] = value;
        return true;
      }
    });
  }
  /**
   * Execute every inline <script> in the shadow tree. Scripts run in an isolated
   * Function scope with a scoped `document` proxy, so element lookups resolve
   * against this card's shadowRoot. Each card gets its own scope, so top-level
   * vars never collide between cards.
   *
   * Only inline scripts (the code the user wrote in the note) are executed.
   * External scripts (`<script src="...">`) are intentionally NOT fetched or run:
   * loading and executing remote code would be a security risk and is disallowed.
   */
  executeScripts(shadow) {
    const docProxy = this.makeDocumentProxy(shadow);
    const scripts = Array.from(shadow.querySelectorAll("script"));
    for (const old of scripts) {
      if (old.hasAttribute("src")) {
        old.remove();
        continue;
      }
      const code = old.textContent;
      old.remove();
      if (!code)
        continue;
      try {
        const fn = new Function(
          "document",
          "shadowRoot",
          "rootNode",
          `"use strict";
${code}`
        );
        fn.call(window, docProxy, shadow, shadow);
      } catch (e) {
        console.error("[html-blocks] script execution error:", e);
      }
    }
  }
  // ========================
  // Source navigation (right sidebar)
  // ========================
  /** Wait for editor to be available on a leaf */
  waitForEditor(leaf, timeout = 1e3) {
    return new Promise((resolve) => {
      const check = () => {
        var _a;
        const editor = (_a = leaf.view) == null ? void 0 : _a.editor;
        if (editor)
          return resolve(editor);
        if (timeout <= 0)
          return resolve(null);
        timeout -= 50;
        setTimeout(check, 50);
      };
      check();
    });
  }
  /** Scroll source to line and highlight it (hover behavior) */
  async scrollSourceToLine(filePath, line) {
    var _a;
    const leaf = await this.ensureSourceLeaf(filePath);
    if (!leaf)
      return;
    const editor = await this.waitForEditor(leaf);
    if (editor) {
      editor.scrollIntoView(
        { from: { line: Math.max(0, line - 5), ch: 0 }, to: { line: line + 5, ch: 0 } },
        true
      );
      const lineLen = ((_a = editor.getLine(line)) == null ? void 0 : _a.length) || 0;
      editor.setSelection({ line, ch: 0 }, { line, ch: lineLen });
    }
  }
  /** Select (highlight) a specific line in source (click behavior) */
  async selectSourceLine(filePath, line) {
    var _a;
    const leaf = await this.ensureSourceLeaf(filePath);
    if (!leaf)
      return;
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    const editor = await this.waitForEditor(leaf);
    if (editor) {
      const lineLen = ((_a = editor.getLine(line)) == null ? void 0 : _a.length) || 0;
      editor.setCursor({ line, ch: 0 });
      editor.scrollIntoView(
        { from: { line: Math.max(0, line - 5), ch: 0 }, to: { line: line + 5, ch: 0 } },
        true
      );
      editor.setSelection({ line, ch: 0 }, { line, ch: lineLen });
      editor.focus();
    }
  }
  /** Ensure the source file is open in right sidebar, in editing mode. Reuse leaf. */
  async ensureSourceLeaf(filePath) {
    var _a, _b;
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian.TFile))
      return null;
    if (this.inspectLeaf) {
      let found = false;
      this.app.workspace.iterateAllLeaves((l) => {
        if (l === this.inspectLeaf)
          found = true;
      });
      if (!found)
        this.inspectLeaf = null;
    }
    if (!this.inspectLeaf) {
      this.inspectLeaf = this.app.workspace.getRightLeaf(false);
      if (!this.inspectLeaf)
        return null;
    }
    const currentFile = (_a = this.inspectLeaf.view) == null ? void 0 : _a.file;
    if (!currentFile || currentFile.path !== filePath) {
      await this.inspectLeaf.openFile(file, { state: { mode: "source", source: true } });
      await new Promise((r) => setTimeout(r, 200));
    }
    const rightSplit = this.app.workspace.rightSplit;
    if (rightSplit == null ? void 0 : rightSplit.collapsed) {
      rightSplit.toggle();
    }
    this.app.workspace.revealLeaf(this.inspectLeaf);
    const view = this.inspectLeaf.view;
    const state = (_b = view == null ? void 0 : view.getState) == null ? void 0 : _b.call(view);
    if (state && (state.mode !== "source" || !state.source)) {
      state.mode = "source";
      state.source = true;
      await view.setState(state, { history: false });
      await new Promise((r) => setTimeout(r, 200));
    }
    return this.inspectLeaf;
  }
  onunload() {
    var _a, _b;
    (_a = this.observer) == null ? void 0 : _a.disconnect();
    this.observer = null;
    this.embedGuards.forEach((g) => g.disconnect());
    this.embedGuards = [];
    this.inspectMode = false;
    if (this.escHandler) {
      document.removeEventListener("keydown", this.escHandler);
    }
    (_b = this.inspectStyleEl) == null ? void 0 : _b.remove();
  }
};
